// Global state (moved from config.js)
const state = {
  dpr: Math.min(window.devicePixelRatio || 1, 3),
  logicalWidth: BASE_WIDTH,
  logicalHeight: BASE_HEIGHT,
  timeStart: performance.now(),
  inputs: {
    pointers: new Map(),
    keys: new Set(),
    gamepads: [],
  },
  seamRatio: 0.5,
  fps: 0,
  frames: 0,
  lastFpsT: performance.now(),
  letterboxCss: { x: 0, y: 0, w: 0, h: 0 },
  timePrev: performance.now(),
  fillViewport: true,
  player: {
    x: 0, z: 0, y: 0.0,
    vy: 0.0,
    grounded: true,
    wallJumpCooldown: 0.0,
    jumpStartY: 0.0,
    angle: 0,
    speed: 0,
    radius: 0.3,
  },
  trail: {
    points: [],
    maxPoints: 420,
    minDist: 0.69/2,
    ttl: 0.69,
  },
  camFollow: { x: 0, y: 0, z: 0 },
  camYaw: 0.0,
  snapBottomFull: false,
  snapTopFull: false,
};
